spring:
  config:
    activate:
      on-profile: local
  jwt:
    secret: ${JWT_SECRET}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_NAME}?serverTimezone=UTC&CharacterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Seoul
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        show-sql: false
        jdbc:
          time_zone: UTC
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: -1
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**
